### ISSUE TITLE
You should look at GNU Hyperbole

### ISSUE THREAD

**Issue by rswgnu** [edrx/eev#1]
I think its easily programmable hyper-button types will solve many of the problems you are trying to solve with eev but more generally and in a better documented fashion, allowing you to work on more of the higher level issues you want to pursue.

**Comment by edrx** [comment]
Hi Robert,

the design principles of eev and Hyperbole are too different! I think
that the "right way" right now is to build a bridge between eev and
Hyperbole, with a mini-tutorial of Hyperbole for eev users (I'm
working on a version 0.0 of that right now, with "eev users" being
"me"), and something correspondent in the other direction...

Can I send some questions? They will have some eev-isms in them, but
note that you can run all their hyperlinks in them with `C-e C-x C-e'
if you have done this:

  (require 'eev-load)

You don't even need the eev-mode keybindings.

I installed Hyperbole from ELPA and these are some of my first
relevant elisp hyperlinks:

  (find-epackage 'hyperbole)
  (code-c-d "elpa" "~/.emacs.d/elpa/")
  (code-c-d "hyperbole" "~/.emacs.d/elpa/hyperbole-7.0.2/" "hyperbole")
  (find-elpafile "hyperbole-readme.txt")
  (find-elpafile "" ""hyperbole)
  (find-hyperbolefile "DEMO")
  (find-hyperbolefile "DEMO" "Action Key is {M-RET}")
  (find-hyperbolefile "DEMO" "Assist Key is {C-u M-RET}")
  (find-hyperbolefile "DEMO" "Press the Action Key within this <(button)>")

  (find-hyperbolenode "")
  (find-hyperbolenode "Installation")
  (find-hyperbolenode "Buttons")

  (eek "M-h M-k M-RET  ;; hkey-either")
  (find-efunctiondescr   'hkey-either)
  (find-efunction        'hkey-either)
  (find-efunction        'action-key)
  (find-efunction        'assist-key)


Here are my first questions...

1. How does hyperbole know that when I open this file

  (find-fline "~/.emacs.d/elpa/hyperbole-7.0.2/DEMO")
  (find-hyperbolefile                         "DEMO")

it has to fontify the strings like "<(button)>"? The file seems to be
in fundamental mode to me...

2. Can you give me a sexp that will perform the same action as M-RET
does when I type it on "<(button)>"? And on "<(keyboard macros)>"? And
on "<(glossary)>"?


  Thanks in advance!!!
    Eduardo Ochs
    http://angg.twu.net/#eev

**Comment by rswgnu** [comment]
> On Apr 20, 2019, at 10:42 AM, Eduardo Ochs <notifications@github.com> wrote:
> 
> Hi Robert,
> 
> the design principles of eev and Hyperbole are too different! I think
> that the "right way" right now is to build a bridge between eev and
> Hyperbole, with a mini-tutorial of Hyperbole for eev users (I'm
> working on a version 0.0 of that right now, with "eev users" being
> "me"), and something correspondent in the other direction...

Sounds good.


> 
> Can I send some questions? They will have some eev-isms in them,

Sure.

> but
> note that you can run all their hyperlinks in them with `C-e C-x C-e'
> if you have done this:
> 
> (require 'eev-load)
> 
> You don't even need the eev-mode keybindings.
> 
> I installed Hyperbole from ELPA and these are some of my first
> relevant elisp hyperlinks:
> 
> (find-epackage 'hyperbole)
> (code-c-d "elpa" "~/.emacs.d/elpa/")
> (code-c-d "hyperbole" "~/.emacs.d/elpa/hyperbole-7.0.2/" "hyperbole")
> (find-elpafile "hyperbole-readme.txt")
> (find-elpafile "" ""hyperbole)
> (find-hyperbolefile "DEMO")
> (find-hyperbolefile "DEMO" "Action Key is {M-RET}")
> (find-hyperbolefile "DEMO" "Assist Key is {C-u M-RET}")
> (find-hyperbolefile "DEMO" "Press the Action Key within this <(button)>")
> 
> (find-hyperbolenode "")
> (find-hyperbolenode "Installation")
> (find-hyperbolenode "Buttons")
> 
> (eek "M-h M-k M-RET ;; hkey-either")
> (find-efunctiondescr 'hkey-either)
> (find-efunction 'hkey-either)
> (find-efunction 'action-key)
> (find-efunction 'assist-key)
> 
> 

I think there are simpler ways to add these as you get familiar with Hyperbole, for example, an action key click on “!simple” will load the elisp of simple.el.  But if they work well for you them that is sufficient.

**Comment by rswgnu** [comment]
> 
>> On Apr 20, 2019, at 10:42 AM, Eduardo Ochs <notifications@github.com> wrote:
>> 
>> Hi Robert,.
>> Here are my first questions...
>> 
>> 1. How does hyperbole know that when I open this file
>> 
>> (find-fline "~/.emacs.d/elpa/hyperbole-7.0.2/DEMO")
>> (find-hyperbolefile "DEMO")
>> 
>> it has to fontify the strings like "<(button)>"? The file seems to be
>> in fundamental mode to me...

A file read hook is added that fontifies explicit buttons in all buffers.

>> 
>> 2. Can you give me a sexp that will perform the same action as M-RET
>> does when I type it on "<(button)>"? And on "<(keyboard macros)>"? And
>> on "<(glossary)>"?

(action-key) and (assist-key) for the complementary help key, though point has to be on the button to activate it.

>> 
>> 
>> Thanks in advance!!!

You’re welcome.

Bob

**Comment by edrx** [comment]
Nope, action-key on these hbuttons

  <(button)>
  <(Smart Mouse Keys)>
  <(toggle-scroll-proportional)>

is not the same as running these sexps

  (button)
  (Smart Mouse Keys)
  (toggle-scroll-proportional)

in the file DEMO... and when I copied the <(...)>s to another file and
try to type M-RET on them I get this "hypb:error":

  (Hyperbole Action Key): No action defined for this context; try another
location.

Hyperbole does look interesting, but I am getting the impression that
our design principles are not only different, they are OPPOSITE! Let
me copy here a paragraph that I sent to Stefan Monnier in a discussion
a few weeks ago... I'll uppercase some parts for emphasis, and add
some [...]s.

     "I've met many people over the years who have been Forth
     enthusiasts in the past, and we often end up discussing what made
     Forth so thrilling to use at that time - and what we can do to
     adapt its ideas to the computers of today. My personal impression
     is that Forth's main points were not the ones that I listed at
     the beginning of this section, and that I said that were easy to
     quantify; rather, what was most important was that NOTHING WAS
     HIDDEN, there were NO COMPLEX DATA STRUCTURES around with
     "don't-look-at-this" parts (think on garbage collection in Lua,
     for example, and Lua's tables - [in Lua] BEGINNERS NEED TO BE
     CONVINCED TO SEE THESE THINGS ABSTRACTLY, as the concrete details
     of the implementation are hard), and everything [in Forth] -
     code, data, dictionaries, stacks - were just linear sequences of
     bytes, that could be read and modified directly if we wished to.
     We had TOTAL FREEDOM, defining new words was quick, and
     experiments were quick to make; that gave us a sense of power
     that was totally different from, say, the one that a Python user
     feels today because he has huge libraries at his fingertips."

     (From: http://angg.twu.net/miniforth-article.html)


My experience with eev is that people have very short attention spans.
I have at most two minutes to show each of the basic principles -

  1) "Lisp can be run from anywhere in Emacs",

  2) "use <f8> on red-star lines to open a terminal running an
     interpreter and make it the target buffer, and <f8> on
     non-red-star lines to send these lines to the target",

and I've tried to prepare material to use these 2 minutes, or 2+2
minutes at most, the best that I can...

I've spent 6 HOURS on Hyperbole in the last days - about 2 of those
writing these e-mails - and I still haven't found neither:

  1) the code that fontifies the "<(...)>"s - though this message


http://lists.gnu.org/archive/html/hyperbole-users/2016-07/msg00004.html

     MAY have a hint,

  2) the function that processes the body of a "<(...)>" - I mean, I
     was able to find these, but I didn't go very far from there...

       (eek "M-h M-k M-RET  ;; hkey-either")
       (find-efunctiondescr   'hkey-either)
       (find-efunction        'hkey-either)
       (find-efunction        'action-key)
       (find-efunction        'assist-key)

  3) the list of regexps that should be at the core of this idea from
     <https://www.gnu.org/software/hyperbole/>:

     "Buttons and Smart Keys: A set of hyperbutton types which supply
     core hypertext and other behaviors. Buttons may be added to
     documents (explicit buttons) with a simple drag between windows,
     no markup language needed. Implicit buttons are patterns of
     regular text that Hyperbole recognizes and then uses to perform
     specified actions, e.g. bug#24568 displays the bug status
     information for that bug number."


This is incredibly frustrating. You are probably not going to answer
anything useful, and my attention window for learning Hyperbole will
close. =( =( =(

  Cheers,
    Eduardo Ochs
    http://angg.twu.net/#eev



P.S.: did you take a look at these section of the eev tutorials? In
the third one I've included a link to a video - just watch it between
"t=16s" and "t=30s".

  (find-eev-quick-intro "2. Evaluating Lisp")
  http://angg.twu.net/eev-intros/find-eev-quick-intro.html#2

  (find-eev-quick-intro "3. Elisp hyperlinks")
  http://angg.twu.net/eev-intros/find-eev-quick-intro.html#3

  (find-eev-quick-intro "6.1. The main key: <F8>")
  http://angg.twu.net/eev-intros/find-eev-quick-intro.html#6.1
  https://www.youtube.com/watch?v=Lj_zKC5BR64&t=16s

  (find-eval-intro "7. Pos-spec-lists")
  http://angg.twu.net/eev-intros/find-eval-intro.html#7




On Sun, 21 Apr 2019 at 15:49, Robert Weiner <notifications@github.com>
wrote:

>

A file read hook is added that fontifies explicit buttons in all buffers.
>
> (action-key) and (assist-key) for the complementary help key, though point
> has to be on the button to activate it.
>
>

**Comment by rswgnu** [comment]
Yes, Hyperbole is largely meant to be used interactively through its abstract interfaces.  As you noted, people have short attention spans.  Hyperbole has been developed across years so there is a lot there to understand under the covers, especially in how the Smart Keys are so smart.

But if you understand Lisp well and we chat a bit, I can probably point you to the parts you want.

-- Bob

**Comment by edrx** [comment]
On IRC?
I use the nick "edrx" on FreeNode. I'm there now.
  Cheers =),
    Eduardo Ochs

**Comment by rswgnu** [comment]
For each explicit button in a directory there is a corresponding entry in the .hypb or _hypb file in the same directory that specifies the button type and the arguments sent to the button’s action (specified by the type).

I feel complex systems are made user friendly by building them out of abstract components that simplify the end user interfaces.  I see your point about Forth in terms of programming languages but not other systems.  Look at the human body.  We survive in part because of our involuntary systems and people navigate the world mostly without any sense of their own biology or the complexity of their cells and organs.

Your needa in wanting to interface Hyperbole to eev are different and I would like to help but I expect you will have to have some patience in learning internals of the system.  There are abstract interfaces that you can use too.

-- Bob

**Comment by rswgnu** [comment]
I am traveling right now and don’t do IRC much, so I meant via email, though you can also call me if you like at +1 203-434-3479 (please don’t publish that number).

Regards,

-- Bob

**Comment by rswgnu** [comment]
Have you tried to use any of Hyperbole’s features as laid out in the DEMO file in your work or are you exclusively looking at it for interfacing to eev?

-- Bob

**Comment by edrx** [comment]
Too late, you've published it yourself! =(
Look at https://github.com/edrx/eev/issues/1 ...

I work half of the week in a campus in a small city called Rio das Ostras,
and I spend the rest of the week in Rio de Janeiro. I'm in Rio de Janeiro
right now and I forget my cell phone in Rio das Ostras. I left it plugged
in the charger, so whatsapp and telegram work, but I can't add new contacts
now and I can't use voice.

I'll try to send you my phone number by private e-mail.
If it doesn't arrive in the next 5 minutes please mail me.
All the eev source files have my e-mail address - for example:
  http://angg.twu.net/eev-current/eev-multiwindow.el.html

  Cheers!
    Eduardo

**Comment by edrx** [comment]
I was able to use some of them, but then I tried to understand how they
worked under the hood and I got lost.

**Comment by bradyt** [comment]
@rswgnu FYI, @edrx is on irc channel #emacs describing that they refuse to delete your phone number because you did not help him with his question.

**Comment by bradyt** [comment]
The phone number has not been completely deleted. You've left it in the quoted message at https://github.com/edrx/eev/issues/1#issuecomment-485282267.

**Comment by edrx** [comment]
Deleted.
Robert, I still don't have your e-mail.

**Comment by rswgnu** [comment]
Yes, let’s move to direct email, rsw@gnu.org, which is a public address.

-- Bob

**Comment by rswgnu** [comment]
Thanks for the deletions.

**Comment by rswgnu** [comment]
> On Apr 21, 2019, at 3:34 PM, Eduardo Ochs <notifications@github.com> wrote:
> 
> Nope, action-key on these hbuttons
> 
> <(button)>
> <(Smart Mouse Keys)>
> <(toggle-scroll-proportional)>
> 
> is not the same as running these sexps
> 
> (button)
> (Smart Mouse Keys)
> (toggle-scroll-proportional)
> 
> in the file DEMO...

Right, the explicit button delimers are not Lisp sexpressions, so there is no relation but action-key is the function that activates such buttons.

> and when I copied the <(...)>s to another file and
> try to type M-RET on them I get this "hypb:error":
> 
> (Hyperbole Action Key): No action defined for this context; try another
> location.
> 

Yes, unfortunately we have never implemented inter-buffer explicit button copying.

> Hyperbole does look interesting, but I am getting the impression that
> our design principles are not only different, they are OPPOSITE!

Probably, if you mean everything associated with a hyperbutton should be visible and embedded within the button’s buffer.  We wanted the in-buffer markup to be minimal.

Bob

**Comment by edrx** [comment]
Update: after these messages in the Hyperbole mailing list I gave up trying to learn Hyperbole - or assigned a very low priority to the task "learn Hyperbole". I am closing this issue. =(

https://lists.gnu.org/archive/html/hyperbole-users/2020-09/msg00013.html
https://lists.gnu.org/archive/html/hyperbole-users/2020-09/threads.html#00013

**Comment by rswgnu** [comment]
Hi Eduardo:

Not sure why after the pointers I provided for easy integration of
Hyperbole implicit buttons with eev that you found that inadequate.  As I
said, if you could just send either individual questions or a message with
a list of questions, we could answer and help guide you but it is difficult
to process long messages with all sorts of information and questions
intermixed, just due to time constraints.

**Comment by edrx** [comment]
Hi Robert,

I found Hyperbole too difficult for me - probably because I am very
bad at using the computer "as a user"... I was spending many hours, or
often days, to understand features that I guess that most people grok
very quickly by trial and error, and then after that many hours to
write each e-mail with questions, and then still some more time to
understand the answers. I was expecting that at some point you would
take a look at eev, try its tutorial, and would understand how I use
it to make this kind of technical communication much quicker and more
precise - or at least you would find a way to translate its ideas to
Hyperbole...

Let's try again when you have time to try eev! =\
  Cheers,
    Eduardo Ochs
    http://angg.twu.net/#eev

**Comment by rswgnu** [comment]
Thanks for the clear explanation.  I have some rime off this week so I hope to take a deeper look.

-- Bob
